-- This script will be automatically generated by Prisma
-- Run: npx prisma migrate dev --name init
-- Or: npx prisma db push

-- Note: When you connect your Neon database, run:
-- 1. npx prisma generate (to generate Prisma Client)
-- 2. npx prisma db push (to push schema to database)
-- 3. Then run the seed script to populate initial data
